twig:
    file_name_pattern: '*.twig'
    date:
        format: d F Y
        interval_format: '%%d days'
        timezone: 'Europe/Paris'
    paths:
        '%kernel.project_dir%/assets': assets
        '%kernel.project_dir%/assets/images': images
        '%kernel.project_dir%/public': public
        '%kernel.project_dir%/assets/mails': mails

when@test:
    twig:
        strict_variables: true
